### PR TITLE
Register Users in Database

### PR DESCRIPTION
**Pull request by ctedtsen**
I created a registration form which adds users to a firebase database (I'll share the database with whoever tests it, just send send me your email, and then share it with everyone else once we're sure it is working properly). When you run npm start you should see a form above the camera access button. I haven't done any error checking or styling yet and will work on that next. This should just add a use to the database.

### CODE REVIEW

**Comment by Jasmine211** [comment]
Hey, I was able to connect with the database! Good job setting that up in the React app. Some changes I suggest are hashing the passwords before creating the new user, that way the password is not stored as plaintext. Also, for the user classification input, I think it would be better to have the user select a given option using the `<select>` element rather than a text input.

**Comment by ctedtsen** [comment]
Good idea! I encrypted the passwords when they are stored in the database now and I also did select for the user classification. I also added error checking to the form and some minor css styling as well. 
Error checking:
-first and last name: must be only letters and be at least two characters long
-username: must be at least three characters, no special characters
-email: must be proper format __@__.com
-password: must contain at least one upper case character, lower case character, number, and special character, must be at least 6 characters long
-password confirm: must match the password

**Comment by Jasmine211** [comment]
Thanks for implementing the suggestions I made! Error checking also looks good to me. This looks ready to merge @joshbernsteint, what do you think?

**Comment by joshbernsteint** [comment]
Looks good to me, merging now

**Pull request merged**
